version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: host.docker.internal #your IP
      KAFKA_CREATE_TOPICS: "wiki-changes:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  spark:
    image: jupyter/all-spark-notebook:dc9744740e12 #this tag has spark v.2.4.5...latest has 3 and doesnt play well with consumer logic
    ports:
      - "8888:8888"
      - "4040-4080:4040-4080"
    links:
      - "kafka:kafka-server" #allows spark notebook to discover kafka service by name "kafka-server"
    volumes:
      - ./notebooks:/home/jovyan/work/notebooks/

# https://hub.docker.com/layers/jupyter/all-spark-notebook/dc9744740e12/images/sha256-1e31465c2dccb82ae249a31ba5412cf25388a12a9b949c76381842dd76b46efd?context=explore